### ISSUE TITLE
Products count can be set below 0

### ISSUE THREAD

**Issue by tobikster** [podsi08/Shopping_list#1]
# Expected behavior
Product's count cannot be set below 0 (ex. -3kg of apples)

# Current behavior
You can set product's count below 0

# Minimal steps to reproduce:
1. Type something in 'product' field.
2. Click down arrow in 'amount' field until there is value below 0.
3. Click 'Add item' button
4. Observe shopping list

**Comment by podsi08** [comment]
Done
